name: Build and Deploy Minecraft Web Client

on:
  push:
    branches:
      - "next"

jobs:
  deploy:
    uses: h4ks-com/k3s-deploy/.github/workflows/k3s-deploy.yaml@main
    with:
      namespace: minecraft
      deployment-name: minecraft-web-client
      services: |
        [
          {
            "context": ".",
            "image": "minecraft-web-client",
            "containers": ["web-client"]
          }
        ]
