name: Vercel Deploy Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  ALIASES: ${{ vars.ALIASES }}
on:
  issue_comment:
    types: [created]
  pull_request_target:
jobs:
  check-trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.AUTO_DEPLOY_PRS }}
      - run: echo ${{ fromJson(vars.AUTO_DEPLOY_PRS) }}
      - run: echo ${{ toJson(contains(fromJson(vars.AUTO_DEPLOY_PRS), github.event.pull_request.number)) }}
      - run: echo ${{ toJson(contains(fromJson(vars.AUTO_DEPLOY_PRS), 120)) }}
  